### PR TITLE
Bug 2088444: Add leftover resources protection

### PR DESCRIPTION
**Pull request by MaysaMacedo**

### CODE REVIEW

**Comment by dulek** [comment]
Okay, previous failure was just quota lease problem.

**Comment by MaysaMacedo** [comment]
/retest
installation failure

**Comment by dulek** [comment]
I replaced the commits with the ones actually merge upstream.

**Comment by MaysaMacedo** [comment]
/override ci/prow/e2e-openstack-kuryr

Overriding as the e2e conformance and openstack tests are passing.

**Pull request merged**
