### PR TITLE
WiP: Protect from Neutron issues

### PR DESCRIPTION
**Pull request by dulek**
Seems like Neutron can return pretty wild data sometimes. This commit makes sure we're protected from ports that doesn't have any address.

Change-Id: Ie2bce807ab4911e40cda34b42099f2e8a1c2aeba

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
@dulek did you see tracebacks indicating this issue? Is it worth to fix upstream?

**Comment by dulek** [comment]
> @dulek did you see tracebacks indicating this issue? Is it worth to fix upstream?

Yes, I've seen them. I'm experimenting here a bit, will fix upstream-first once I have it figured out.

**Comment by dulek** [comment]
Kuryr is EOL in OpenShift.

**Pull request closed without merging**
