### PR TITLE
[release-4.6] Bug 1968418: Fixing bug, Kuryr-Controller crashes when it's missing the status

### PR DESCRIPTION
**Pull request by dulek**
Cherry pick of #501.

### CODE REVIEW

**Comment by dulek** [comment]
/hold

I bet I should test this first, the cherry-pick wasn't trivial.

**Comment by dulek** [comment]
Ha, good I tested this, I made quite a mistake resolving conflicts.

**Comment by dulek** [comment]
/hold cancel

Alright, this seems to work now.

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.70

approved

**Pull request merged**
