### PR TITLE
Bug 2013496: Reap zombie child processes in CNI daemon service

### PR DESCRIPTION
**Pull request by MaysaMacedo**
kuryr-daemon does not handle reaping of zombie child processes which are
not started by itself. But being PID 1 inside the docker container, it
is expected to execute waitpid() for all its children.

This change runs a thread that waits for any killed child processes,
effectively reaping any zombie processes. This fixes the problem of
zombie process accumulation on long running deployments.

Change-Id: I48a665b089bf2d09eec9909e300a64f6e15cbdfe
Closes-Bug: 1854134
Signed-off-by: Yash Gupta <y.gupta@samsung.com>

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/hold

Needs testing.

**Comment by dulek** [comment]
Do we still need this? Do I remember correctly that this was an attempt to solve the increased CPU usage?

**Comment by MaysaMacedo** [comment]
> Do we still need this? Do I remember correctly that this was an attempt to solve the increased CPU usage?

Not really. This was an attempt to fix issues seen in 3.11 a while ago and I needed the img built with this. Even with this fix I still saw some zombie processes.
I will close this and re-open when we decide to tackle this again.

**Comment by dulek** [comment]
Ah right, that's for 3.11.

**Pull request merged**
