### PR TITLE
Bug 1786298: Bunch of kuryr-daemon NetlinkError fixes

### PR DESCRIPTION
**Pull request by dulek**
This PR collects 3 patches related to fixing NetlinkError occasionally happening in kuryr-daemon.

### CODE REVIEW

**Comment by dulek** [comment]
Eh, needs https://github.com/openshift/kuryr-kubernetes/pull/294 to get in first.

**Comment by sdodson** [comment]
Please clear the hold if you'd like for this to go in.

**Comment by dulek** [comment]
/hold cancel

Okay, I just tested this installs just fine.

**Comment by dulek** [comment]
@sdodson: Can you still consider approving this?

**Pull request merged**
