### PR TITLE
DNM: Update minimum openstacksdk version to 0.59.0

### PR DESCRIPTION
**Pull request by dulek**
This commit bumps openstacksdk to at least 0.59.0 in requirements.txt
and removes the workarounds that we carried to actually support 0.36.0.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
`	clusteroperator/network is degraded because Deployment "/openshift-kuryr/kuryr-controller" rollout is not making progress - pod kuryr-controller-6786997c9d-86zz7 is in CrashLoopBackOff State`

Looks like the must-gather didn't collect the appropriate logs because Kuryr was not happy. It might be worth accessing the cluster while installation is happening.

**Comment by dulek** [comment]
Ouch.

**Comment by dulek** [comment]
Okay, this should work better. I have troubles updating the upstream commit now, but let's see if this works.

**Comment by dulek** [comment]
/retest

Weird, but nothing alarming in Kuryr logs.

**Comment by dulek** [comment]
/retest

One more time.

**Comment by dulek** [comment]
This is on hold and let's keep it. I'd rather merge this once the patch is in upstream too.

**Pull request closed without merging**
